import { MapLayerConfig } from "../types/isie";

const PLACEHOLDER_SOURCE = "PROVIDER NOT CONNECTED";
const NO_LATENCY = "NO DATA / LATENCY UNAVAILABLE";

export const DEFAULT_MAP_LAYERS: MapLayerConfig[] = [
  {
    id: "layer-red-zones",
    name: "Exercise zone overlay (placeholder)",
    category: "HAZARD_ZONES",
    description: "UI control placeholder only. No hazard boundaries or risk classifications are loaded.",
    enabled: false,
    opacity: 0.85,
    sourceProvider: PLACEHOLDER_SOURCE,
    latencySpec: NO_LATENCY,
  },
  {
    id: "layer-sentinel1-sar",
    name: "Satellite imagery overlay (placeholder)",
    category: "SATELLITE",
    description: "No satellite imagery or remote-sensing products are connected.",
    enabled: false,
    opacity: 0.65,
    sourceProvider: PLACEHOLDER_SOURCE,
    latencySpec: NO_LATENCY,
  },
  {
    id: "layer-sentinel2-optical",
    name: "Optical imagery overlay (placeholder)",
    category: "SATELLITE",
    description: "No optical imagery or change-detection products are connected.",
    enabled: false,
    opacity: 0.7,
    sourceProvider: PLACEHOLDER_SOURCE,
    latencySpec: NO_LATENCY,
  },
  {
    id: "layer-cwc-hydrology",
    name: "Hydrology overlay (placeholder)",
    category: "HYDROLOGICAL",
    description: "No river gauges, thresholds, reservoir, or discharge measurements are connected.",
    enabled: false,
    opacity: 0.9,
    sourceProvider: PLACEHOLDER_SOURCE,
    latencySpec: NO_LATENCY,
  },
  {
    id: "layer-imd-radar",
    name: "Weather overlay (placeholder)",
    category: "HYDROLOGICAL",
    description: "No weather observations, forecasts, or alert vectors are connected.",
    enabled: false,
    opacity: 0.6,
    sourceProvider: PLACEHOLDER_SOURCE,
    latencySpec: NO_LATENCY,
  },
  {
    id: "layer-carrying-capacity",
    name: "Capacity overlay (placeholder)",
    category: "INFRASTRUCTURE",
    description: "No shelter, healthcare, supply, or infrastructure capacity measurements are connected.",
    enabled: false,
    opacity: 0.8,
    sourceProvider: PLACEHOLDER_SOURCE,
    latencySpec: NO_LATENCY,
  },
  {
    id: "layer-evacuation-corridors",
    name: "Route overlay (placeholder)",
    category: "INFRASTRUCTURE",
    description: "No route safety, bridge condition, clearance, or evacuation routing is provided.",
    enabled: false,
    opacity: 0.75,
    sourceProvider: PLACEHOLDER_SOURCE,
    latencySpec: NO_LATENCY,
  },
  {
    id: "layer-population-density",
    name: "Population overlay (placeholder)",
    category: "POPULATION",
    description: "No population or vulnerability data is connected.",
    enabled: false,
    opacity: 0.5,
    sourceProvider: PLACEHOLDER_SOURCE,
    latencySpec: NO_LATENCY,
  },
];

const unavailable = "Reference only. No access, endpoint, data rights, license, credentials, or suitability have been verified; no connection is implemented.";

export const AUTHORITATIVE_SOURCES = [
  {
    id: "weather-reference",
    code: "REFERENCE-WEATHER",
    name: "Weather-data provider (unselected)",
    type: "Potential source category",
    endpointCategory: "Not configured",
    status: "STANDBY_UNCONNECTED",
    description: unavailable,
    referenceUrl: "",
  },
  {
    id: "hydrology-reference",
    code: "REFERENCE-HYDROLOGY",
    name: "Hydrology-data provider (unselected)",
    type: "Potential source category",
    endpointCategory: "Not configured",
    status: "STANDBY_UNCONNECTED",
    description: unavailable,
    referenceUrl: "",
  },
  {
    id: "earth-observation-reference",
    code: "REFERENCE-EARTH-OBSERVATION",
    name: "Earth-observation provider (unselected)",
    type: "Potential source category",
    endpointCategory: "Not configured",
    status: "STANDBY_UNCONNECTED",
    description: unavailable,
    referenceUrl: "",
  },
  {
    id: "infrastructure-reference",
    code: "REFERENCE-INFRASTRUCTURE",
    name: "Infrastructure and route data provider (unselected)",
    type: "Potential source category",
    endpointCategory: "Not configured",
    status: "STANDBY_UNCONNECTED",
    description: unavailable,
    referenceUrl: "",
  },
];
